Airbnb_dbt:
  outputs:
    dev:
      account: SNBYTEY-EO39087
      database: VIKRAM_DBT
      password: Training123456$
      role: ACCOUNTADMIN
      schema: dbt_target
      threads: 2
      type: snowflake
      user: sep2026learn
      warehouse: DBT_LARGE_WH
  target: dev
