Airbnb_dbt:
  outputs:
    dev:
      account: VYIIKYM-GN15832
      database: VIKRAM_DBT
      password: Training123456$
      role: ACCOUNTADMIN
      schema: dbt_target
      threads: 2
      type: snowflake
      user: aug2026learn
      warehouse: DBT_LARGE_WH
  target: dev
